RFC WIP Chaos: Implement a non-verbose stack trace system
```julia
function lorenz!(du,u,p,t)
 du[1] = 10.0(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3] * p
end
u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz!,u0,tspan)
sol = solve(prob,Tsit5())
```

Before:

After:

```julia
ERROR: DomainError with -1.0:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).
DomainError detected in the user `f` function. This occurs when the domain of a function is violated.
For example, `log(-1.0)` is undefined because `log` of a real number is defined to only output real
numbers, but `log` of a negative number is complex valued and therefore Julia throws a DomainError
by default. Cases to be aware of include:

* `log(x)`, `sqrt(x)`, `cbrt(x)`, etc. where `x<0`
* `x^y` for `x<0` floating point `y` (example: `(-1.0)^(1/2) == im`)

Within the context of SciML, this error can occur within the solver process even if the domain constraint
would not be violated in the solution due to adaptivity. For example, an ODE solver or optimization
routine may check a step at `new_u` which violates the domain constraint, and if violated reject the
step and use a smaller `dt`. However, the throwing of this error will have halted the solving process.

Thus the recommended fix is to replace this function with the equivalent ones from NaNMath.jl
(https://github.com/JuliaMath/NaNMath.jl) which returns a NaN instead of an error. The solver will then
effectively use the NaN within the error control routines to reject the out of bounds step. Additionally,
one could perform a domain transformation on the variables so that such an issue does not occur in the
definition of `f`.

For more information, check out the following FAQ page:
https://docs.sciml.ai/Optimization/stable/API/FAQ/#The-Solver-Seems-to-Violate-Constraints-During-the-Optimization,-Causing-DomainErrors,-What-Can-I-Do-About-That?

Some of the types have been truncated in the stacktrace for improved reading. To emit complete information
in the stack trace, evaluate `SciMLBase.VERBOSE_PRINT[] = true` and re-run the code.


Stacktrace:
  [1] throw_complex_domainerror(f::Symbol, x::Float64)
    @ Base.Math .\math.jl:33
  [2] _log(x::Float64, base::Val{:ℯ}, func::Symbol)
    @ Base.Math .\special\log.jl:301
  [3] log
    @ .\special\log.jl:267 [inlined]
  [4] log(x::Int64)
    @ Base.Math .\math.jl:1491
  [5] lorenz!(du::Vector{Float64}, u::Vector{Float64}, p::SciMLBase.NullParameters, t::Float64)
    @ Main c:\Users\accou\OneDrive\Computer\Desktop\test.jl:106
  [6] (::SciMLBase.Void{typeof(lorenz!)})(::Vector{Float64}, ::Vararg{Any})
    @ SciMLBase C:\Users\accou\.julia\dev\SciMLBase\src\utils.jl:468
  [7] (::FunctionWrappers.CallWrapper{Nothing})(f::SciMLBase.Void{typeof(lorenz!)}, arg1::Vector{Float64}, arg2::Vector{Float64}, arg3::SciMLBase.NullParameters, arg4::Float64)
    @ FunctionWrappers C:\Users\accou\.julia\packages\FunctionWrappers\Q5cBx\src\FunctionWrappers.jl:65
  [8] macro expansion
    @ C:\Users\accou\.julia\packages\FunctionWrappers\Q5cBx\src\FunctionWrappers.jl:137 [inlined]
  [9] do_ccall
    @ C:\Users\accou\.julia\packages\FunctionWrappers\Q5cBx\src\FunctionWrappers.jl:125 [inlined]
 [10] FunctionWrapper
    @ C:\Users\accou\.julia\packages\FunctionWrappers\Q5cBx\src\FunctionWrappers.jl:144 [inlined]
 [11] _call
    @ C:\Users\accou\.julia\packages\FunctionWrappersWrappers\9XR0m\src\FunctionWrappersWrappers.jl:12 [inlined]
 [12] FunctionWrappersWrapper
    @ C:\Users\accou\.julia\packages\FunctionWrappersWrappers\9XR0m\src\FunctionWrappersWrappers.jl:10 [inlined]
 [13] ODEFunction
    @ C:\Users\accou\.julia\dev\SciMLBase\src\scimlfunctions.jl:2106 [inlined]
 [14] initialize!(integrator::ODEIntegrator{true, Tsit5{Static.False, …}, Vector{Float64}, Float64, …}, cache::Tsit5Cache{Vector{Float64}, …})
    @ OrdinaryDiffEq C:\Users\accou\.julia\packages\OrdinaryDiffEq\0Pm1I\src\perform_step\low_order_rk_perform_step.jl:766
 [15] __init(prob::ODEProblem{true,Vector{Float64},Tuple{Float64, Float64},…}, alg::Tsit5{Static.False, …}, timeseries_init::Tuple{}, ts_init::Tuple{}, ks_init::Tuple{}, recompile::Type{Val{true}}; saveat::Tuple{}, tstops::Tuple{}, d_discontinuities::Tuple{}, save_idxs::Nothing, save_everystep::Bool, save_on::Bool, save_start::Bool, save_end::Nothing, callback::Nothing, dense::Bool, calck::Bool, dt::Float64, dtmin::Nothing, dtmax::Float64, force_dtmin::Bool, adaptive::Bool, gamma::Rational{Int64}, abstol::Nothing, reltol::Nothing, qmin::Rational{Int64}, qmax::Int64, qsteady_min::Int64, qsteady_max::Int64, beta1::Nothing, beta2::Nothing, qoldinit::Rational{Int64}, controller::Nothing, fullnormalize::Bool, failfactor::Int64, maxiters::Int64, internalnorm::typeof(DiffEqBase.ODE_DEFAULT_NORM), internalopnorm::typeof(LinearAlgebra.opnorm), isoutofdomain::typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), unstable_check::typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), verbose::Bool, timeseries_errors::Bool, dense_errors::Bool, advance_to_tstop::Bool, stop_at_next_tstop::Bool, initialize_save::Bool, progress::Bool, progress_steps::Int64, progress_name::String, progress_message::typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), userdata::Nothing, allow_extrapolation::Bool, initialize_integrator::Bool, alias_u0::Bool, alias_du0::Bool, initializealg::OrdinaryDiffEq.DefaultInit, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ OrdinaryDiffEq C:\Users\accou\.julia\packages\OrdinaryDiffEq\0Pm1I\src\solve.jl:499
 [16] __init (repeats 5 times)
    @ C:\Users\accou\.julia\packages\OrdinaryDiffEq\0Pm1I\src\solve.jl:10 [inlined]
 [17] #__solve#626
    @ C:\Users\accou\.julia\packages\OrdinaryDiffEq\0Pm1I\src\solve.jl:5 [inlined]
 [18] __solve
    @ C:\Users\accou\.julia\packages\OrdinaryDiffEq\0Pm1I\src\solve.jl:1 [inlined]
 [19] #solve_call#22
    @ C:\Users\accou\.julia\packages\DiffEqBase\jSoyI\src\solve.jl:496 [inlined]
 [20] solve_call
    @ C:\Users\accou\.julia\packages\DiffEqBase\jSoyI\src\solve.jl:466 [inlined]
 [21] #solve_up#29
    @ C:\Users\accou\.julia\packages\DiffEqBase\jSoyI\src\solve.jl:919 [inlined]
 [22] solve_up
    @ C:\Users\accou\.julia\packages\DiffEqBase\jSoyI\src\solve.jl:892 [inlined]
 [23] #solve#27
    @ C:\Users\accou\.julia\packages\DiffEqBase\jSoyI\src\solve.jl:829 [inlined]
 [24] solve(prob::ODEProblem{true,Vector{Float64},Tuple{Float64, Float64},…}, args::Tsit5{Static.False, …})
    @ DiffEqBase C:\Users\accou\.julia\packages\DiffEqBase\jSoyI\src\solve.jl:819
 [25] top-level scope
    @ c:\Users\accou\OneDrive\Computer\Desktop\test.jl:111
```